name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DISPLAY: :99
  WDM_GITHUBTOKEN: ${{ secrets.WDM_GITHUBTOKEN }}
  MOZ_PROFILER_STARTUP: 1
  MOZ_PROFILER_SHUTDOWN: geckodriver-profile.json

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        java: [ 8 ]
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Start Xvfb
      run: Xvfb :99 &
    - name: Run tests
      run: mvn -B test
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: json-files
        path: |
          *.json
